// Country Cycles Killearn — KEEF Diagnostic Engine (web port)
// Mandated caveats, contact details, CTA copy, and result-message templates.
//
// SAFETY-CRITICAL: the strings in CAVEATS are mandated wording and must be
// rendered verbatim. The build pipeline must include a test that fails if a
// common misspelling of the word "in-store" appears in user-facing output.

export const CAVEATS = {
  long:
    'This tool provides general guidance only. Bike faults cannot be fully diagnosed or validated without speaking to our in-store team at Country Cycles Killearn. If you are unsure, if the bike feels unsafe, or if the issue affects braking, steering, wheels, frame, forks, e-bike electronics, or battery systems, please do not ride the bike until it has been checked by a qualified mechanic.',
  short:
    "Advice cannot be validated without speaking to our in-store team. If in doubt, don't ride — contact Country Cycles.",
};

export const CONTACT = {
  shopName: 'Country Cycles',
  phone: '01360 550 372',
  email: 'info@country-cycles.com',
  bookingUrl: '',
  address: 'Oakwood Garden Centre, Killearn, Glasgow G63 9PT',
  website: 'https://www.country-cycles.com',
  instagramUrl: 'ADD_INSTAGRAM_LINK',
};

export const CTAS = {
  NONE: { label: '', urgent: false },
  BOOK_WORKSHOP: { label: 'Book a workshop slot', urgent: false },
  CALL_SHOP_URGENT: { label: 'Call Country Cycles', urgent: true },
  CALL_SHOP_BATTERY: {
    label: 'Call Country Cycles — battery issue',
    urgent: true,
    extra:
      "Stop charging the battery. Get it away from anything that can catch fire. Don't take it indoors. Phone the shop.",
  },
};

export const RESULT_TEMPLATES = {
  // ============= GREEN =============
  GREEN_BRAKES_WHEEL_RESEAT: {
    id: 'GREEN_BRAKES_WHEEL_RESEAT', tier: 'GREEN', keefPose: 'wrench_thumb',
    headline: "Aye, that'll be the wheel not seated right.",
    body: "Common after a wheel-out, transport, or a knock. Open the quick-release or thru-axle, drop the wheel back in straight against the dropouts, close it firm. Spin the wheel — rub gone? You're sorted.",
    actionLine: "If the rub comes back, bring it in. Anything else playing up?",
    ctaId: 'NONE',
  },
  GREEN_GEARS_NEW_CABLE_BEDDING: {
    id: 'GREEN_GEARS_NEW_CABLE_BEDDING', tier: 'GREEN', keefPose: 'idea',
    headline: 'New cables stretch in. Nae bother.',
    body: "First couple of hundred kilometres on new cables, the indexing drifts a wee bit. That's normal — it's the cable bedding in, not a fault. If you bought the bike from us, your free first service will sort it.",
    actionLine: 'Book a slot for a quick re-tension if it persists.',
    ctaId: 'BOOK_WORKSHOP',
  },
  GREEN_GEARS_CROSS_CHAINING: {
    id: 'GREEN_GEARS_CROSS_CHAINING', tier: 'GREEN', keefPose: 'idea',
    headline: "That's cross-chaining, not a fault.",
    body: "Big chainring with the biggest sprocket, or wee chainring with the smallest sprocket — the chain runs at a daft angle and rubs the front mech. Shift to a more central gear combo and the noise will go.",
    actionLine: 'Anything else playing up?',
    ctaId: 'NONE',
  },
  GREEN_CHAIN_DROP_ONEOFF: {
    id: 'GREEN_CHAIN_DROP_ONEOFF', tier: 'GREEN', keefPose: 'wrench_thumb',
    headline: 'One-off chain drop. It happens.',
    body: "Heavy shift, bumpy ground, the chain hops off. Lift it back onto the chainring with your fingers — mind the oil. Ride gently for a wee while and watch for repeats.",
    actionLine: 'If it drops again the same ride, bring it in for a look.',
    ctaId: 'NONE',
  },
  GREEN_CHAIN_STIFF_LINK_RELUBE: {
    id: 'GREEN_CHAIN_STIFF_LINK_RELUBE', tier: 'GREEN', keefPose: 'idea',
    headline: 'Sounds like a stiff link from a dry chain.',
    body: 'Spin the chain backwards through the rear mech and watch for one link that jumps the jockey wheel — that one. A drop of chain lube on each side of that link, flex it gently side to side, wipe the excess. Should free up.',
    actionLine: 'If it persists after a clean and lube, book a slot.',
    ctaId: 'BOOK_WORKSHOP',
    needs: [
      { label: 'Chain lube',     url: 'https://www.country-cycles.com/peatys-linklube-all-weather-120ml-box-12-single.html' },
      { label: 'Degreaser',      url: 'https://www.country-cycles.com/peatys-1000-ml-foaming-drivetrain-degreaser-box-12.html' },
      { label: 'A clean rag',    search: 'cleaning' },
    ],
  },
  GREEN_TYRES_PUNCTURE_TUBED: {
    id: 'GREEN_TYRES_PUNCTURE_TUBED', tier: 'GREEN', keefPose: 'wrench_thumb',
    headline: "Standard puncture. Tube swap and you're away.",
    body: "Replace the tube. Before fitting, run a finger carefully round the inside of the tyre — if a thorn or shard caused the puncture and it's still in there, the new tube goes the same way.",
    actionLine: "If you're getting repeated punctures in the same spot, that's a workshop job.",
    ctaId: 'NONE',
    needs: [
      { label: 'Replacement inner tube', search: 'inner tube' },
      { label: 'Tyre levers',            search: 'tyre lever' },
      { label: 'Mini pump',              url: 'https://www.country-cycles.com/pump-truflo-electron-compact-electric.html' },
    ],
  },
  GREEN_TYRES_TUBELESS_TOPUP: {
    id: 'GREEN_TYRES_TUBELESS_TOPUP', tier: 'GREEN', keefPose: 'idea',
    headline: 'Sealant dries out — top it up and reinflate.',
    body: "Tubeless sealant typically lasts two to six months depending on temperature and how much you ride. Going flat overnight with no obvious puncture usually means it's dried up. Top up through the valve, reinflate, spin the wheel to spread it.",
    actionLine: "If it won't hold air after a top-up, book a slot.",
    ctaId: 'BOOK_WORKSHOP',
    needs: [
      { label: 'Tubeless sealant',     url: 'https://www.country-cycles.com/peatys-120-ml-tubeless-sealant-trail-pouch-12-unit.html' },
      { label: 'Plug pack (for cuts)', url: 'https://www.country-cycles.com/dynaplug-plug-pack-3-x-soft-nose-and-2-x-mega-plug.html' },
      { label: 'Valve core remover',   search: 'valve core' },
    ],
  },
  GREEN_SUSPENSION_SAG: {
    id: 'GREEN_SUSPENSION_SAG', tier: 'GREEN', keefPose: 'idea',
    headline: 'Likely just air pressure.',
    body: "Suspension forks and shocks lose a bit of air over time. Set sag with a shock pump to the manufacturer's recommended pressure for your weight. If you don't have a shock pump, we can set it in store — it's a five-minute job.",
    actionLine: 'No shock pump? Pop in, we keep one on the counter.',
    ctaId: 'BOOK_WORKSHOP',
    needs: [
      { label: 'Shock pump', search: 'shock pump' },
    ],
  },
  GREEN_EBIKE_LEGAL_LIMIT_NORMAL: {
    id: 'GREEN_EBIKE_LEGAL_LIMIT_NORMAL', tier: 'GREEN', keefPose: 'idea',
    headline: "That's the legal assist limit. Not a fault.",
    body: "UK law caps electric assist at 15.5 mph (25 km/h) on EAPCs. Above that, the motor stops helping — you can keep pedalling, but you're under your own steam. That's by design, not a fault.",
    actionLine: 'Anything else playing up?',
    ctaId: 'NONE',
  },
  GREEN_EBIKE_COLD_RANGE: {
    id: 'GREEN_EBIKE_COLD_RANGE', tier: 'GREEN', keefPose: 'idea',
    headline: 'Cold weather flattens lithium batteries. Normal.',
    body: "Below 5°C you'll lose 10–30% of usable range. Store the battery indoors at room temperature, charge it inside, only fit it to the bike when you're heading out. You'll get most of the range back as the weather warms.",
    actionLine: "If the range stays low in mild weather, that's a different conversation — book a slot.",
    ctaId: 'BOOK_WORKSHOP',
  },

  // ============= AMBER =============
  AMBER_GENERIC: {
    id: 'AMBER_GENERIC', tier: 'AMBER', keefPose: 'thinking',
    headline: "That's a workshop job.",
    body: "From what you've described, this needs hands on it before you ride hard. Not unsafe to wheel home or transport, but get a slot booked.",
    actionLine: 'Book a workshop slot — the team will sort it.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_NOT_SURE: {
    id: 'AMBER_NOT_SURE', tier: 'AMBER', keefPose: 'thinking',
    headline: "Right — let's get eyes on it.",
    body: "I'd rather see it than guess. If the bike feels off, it's worth a wee check before you ride it again.",
    actionLine: 'Book a workshop slot and we will take a proper look.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_BRAKES_PADS_OR_CABLE: {
    id: 'AMBER_BRAKES_PADS_OR_CABLE', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Sounds like pads or cable tension.',
    body: "Cable brake, lever firm but the bike doesn't pull up the way it used to — usually means worn pads or a stretched cable. Both are workshop jobs.",
    actionLine: 'Book a slot — quick fix in store.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_BRAKES_CALIPER_ALIGN: {
    id: 'AMBER_BRAKES_CALIPER_ALIGN', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Caliper needs realigning.',
    body: "Light disc rub with the bike still stopping fine usually means the caliper is sitting a hair off centre. Quick re-centre in the workshop.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_GEARS_INDEX: {
    id: 'AMBER_GEARS_INDEX', tier: 'AMBER', keefPose: 'thinking',
    headline: "Indexing's drifted. Workshop job.",
    body: "Skipping on one specific gear, hesitant shifting, a wee tick that won't go away — usually a cable tension or limit-screw tweak.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_GEARS_HANGER_SUSPECT: {
    id: 'AMBER_GEARS_HANGER_SUSPECT', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Suspect bent hanger after that fall.',
    body: "Drive-side fall and now the gears are off — the hanger (the wee bracket the rear mech bolts to) is designed to bend before the frame does. Don't ride it hard until we have checked: a hanger that fails sends the mech into the spokes.",
    actionLine: "Wheel it in or book a slot. Don't ride hard.",
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_GEARS_DRIVETRAIN_WORN: {
    id: 'AMBER_GEARS_DRIVETRAIN_WORN', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Drivetrain wear. Time for a measure-up.',
    body: "Skipping across all the gears under load usually means the chain has stretched and the cassette is worn. We can measure the chain in store — if it's gone, the cassette likely has too.",
    actionLine: 'Book a slot for a drivetrain check.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_GEARS_ELECTRONIC: {
    id: 'AMBER_GEARS_ELECTRONIC', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Electronic shifting acting up.',
    body: "Erratic shifts on Di2, AXS, or EPS usually point to charging, pairing, or a firmware issue. We have the diagnostic tools in store.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_CHAIN_REPEATED_DROPS: {
    id: 'AMBER_CHAIN_REPEATED_DROPS', tier: 'AMBER', keefPose: 'thinking',
    headline: "Repeated drops. Something's not right.",
    body: "Could be a worn chainring, chain length off, missing chain catcher, or a tired narrow-wide ring on a 1x setup. Workshop call.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_CHAIN_WORN: {
    id: 'AMBER_CHAIN_WORN', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Chain likely worn. Get it measured.',
    body: "Chains are the cheapest drivetrain wear part — and ignoring wear chews through cassettes and chainrings. We will measure it on a chain gauge in store.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_TYRES_REPEATED_PUNCTURES: {
    id: 'AMBER_TYRES_REPEATED_PUNCTURES', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Repeated punctures same spot. Worth a look.',
    body: "Could be rim tape, a hidden cut in the tyre, or a worn casing letting glass through. We will check the tyre and rim properly.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_TYRES_TUBELESS_BEAD: {
    id: 'AMBER_TYRES_TUBELESS_BEAD', tier: 'AMBER', keefPose: 'thinking',
    headline: "Bead won't seat — workshop has the gear.",
    body: "Tubeless beads sometimes need a compressor or a tubeless inflator to pop on. A track pump won't do it.",
    actionLine: 'Bring it in.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_WHEELS_MILD_BUCKLE: {
    id: 'AMBER_WHEELS_MILD_BUCKLE', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Wheel out of true — needs a spoke job.',
    body: "Mild wobble with no broken spokes is a tensioning job in the truing stand. Don't ride hard or off-road until it's done.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_WHEELS_LOOSE_SPOKE: {
    id: 'AMBER_WHEELS_LOOSE_SPOKE', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Loose spoke. Get it tensioned.',
    body: "One loose spoke now means more loose spokes soon — the load is spreading round the wheel. Don't ride hard.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_TYRES_SQUARED_OFF: {
    id: 'AMBER_TYRES_SQUARED_OFF', tier: 'AMBER', keefPose: 'thinking',
    headline: "Tyre's worn out.",
    body: "Tread squared off, centre worn, casing starting to show — replacement is due. We'll fit a like-for-like or recommend a swap.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_HEADSET_STIFF: {
    id: 'AMBER_HEADSET_STIFF', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Headset stiff or notchy.',
    body: "Could be over-tightened preload, brinelled bearings, or cable routing too tight on a modern integrated cockpit. Workshop call.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_BB_CREAK: {
    id: 'AMBER_BB_CREAK', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Creak from the bottom bracket area.',
    body: "Creaks travel through frames — could be the BB, pedals, chainring bolts, seatpost, or saddle rails. We'll trace it down properly in store.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_BB_GRIND: {
    id: 'AMBER_BB_GRIND', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Bottom bracket bearings on the way out.',
    body: 'Grinding or roughness when pedalling usually means the BB bearings are done. Replacement job in the workshop.',
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_SUSPENSION_LOWER_SERVICE: {
    id: 'AMBER_SUSPENSION_LOWER_SERVICE', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Suspension service due.',
    body: 'Oil weeping onto the stanchions means the seals are tired. Most forks and shocks want a lower service every 50 hours of riding. Workshop job.',
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_SUSPENSION_DROPPER: {
    id: 'AMBER_SUSPENSION_DROPPER', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Dropper post needs adjusting or servicing.',
    body: "Sluggish drop or refuses to extend — usually cable tension or an internal service. We have the kit in store.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_EBIKE_CHARGER_FAILURE: {
    id: 'AMBER_EBIKE_CHARGER_FAILURE', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Sounds like the charger.',
    body: "No LED on the charger when plugged into the wall (with no battery attached) usually points at the charger itself. Bring the charger AND the battery in — we test both.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_EBIKE_ERROR_CODE: {
    id: 'AMBER_EBIKE_ERROR_CODE', tier: 'AMBER', keefPose: 'thinking',
    headline: "We've logged the error code. Workshop call.",
    body: "Manufacturer error codes change between firmware versions, so I won't guess. The team in store will look it up against the current dealer manual.",
    actionLine: 'Book a slot — bring the bike, the battery, and the charger.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_EBIKE_RANGE_LOSS_AGE: {
    id: 'AMBER_EBIKE_RANGE_LOSS_AGE', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Battery age. Worth a capacity test.',
    body: 'Most e-bike batteries lose noticeable capacity after 500–1000 full charge cycles or 3+ years. We can run a capacity test in store and tell you where it is.',
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_EBIKE_INTERMITTENT: {
    id: 'AMBER_EBIKE_INTERMITTENT', tier: 'AMBER', keefPose: 'thinking',
    headline: 'Intermittent display or motor — diagnostic time.',
    body: "Intermittents are the worst kind of fault to chase remotely. We will plug it into the diagnostic tool and read the live data.",
    actionLine: 'Book a slot.',
    ctaId: 'BOOK_WORKSHOP',
  },
  AMBER_KIDS_SIZING: {
    id: 'AMBER_KIDS_SIZING', tier: 'AMBER', keefPose: 'idea',
    headline: 'Sounds like the bike has been outgrown.',
    body: "Knees hitting bars, saddle at max post height, heels hitting the rear wheel — that's a sizing issue, not a fault. Time for a sizing chat in store.",
    actionLine: 'Pop in for a sizing conversation.',
    ctaId: 'BOOK_WORKSHOP',
  },

  // ============= RED =============
  RED_GENERIC_DO_NOT_RIDE: {
    id: 'RED_GENERIC_DO_NOT_RIDE', tier: 'RED', keefPose: 'stop',
    headline: "Stop. Don't ride that bike.",
    body: "From what you've described, this is safety-critical. Wheel it home if you have to. Phone the shop.",
    actionLine: 'Phone Country Cycles. We will sort it.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_BRAKES_LEVER_TO_BAR: {
    id: 'RED_BRAKES_LEVER_TO_BAR', tier: 'RED', keefPose: 'stop',
    headline: 'Lever to the bar means no brake.',
    body: "Air in the system or fluid leaking out — either way, that brake won't stop you. Don't ride it. Wheel it home.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_BRAKES_HYDRAULIC_LEAK: {
    id: 'RED_BRAKES_HYDRAULIC_LEAK', tier: 'RED', keefPose: 'stop',
    headline: 'Hydraulic leak. Do not ride.',
    body: "Brake fluid where it shouldn't be means the brake will fail mid-ride. If any fluid touched the rotor or pads, those need replacing — they will not work properly again.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_BRAKES_CONTAMINATED: {
    id: 'RED_BRAKES_CONTAMINATED', tier: 'RED', keefPose: 'stop',
    headline: 'Contaminated pads or rotor. Stop.',
    body: "Oil, fluid, or chain lube on a disc rotor or pads — that brake won't bite properly until both are cleaned or replaced. Don't ride it.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_BRAKES_SNAPPED_CABLE: {
    id: 'RED_BRAKES_SNAPPED_CABLE', tier: 'RED', keefPose: 'stop',
    headline: 'Snapped cable. Do not ride.',
    body: 'No rear brake cable means no rear brake. Wheel it home.',
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_BRAKES_ROTOR_BURN: {
    id: 'RED_BRAKES_ROTOR_BURN', tier: 'RED', keefPose: 'stop',
    headline: 'Burning smell or vibration from the brake. Stop.',
    body: "Overheated brake, contaminated pads, or a warped rotor. That brake is unreliable and getting worse with every use.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_GEARS_BENT_DERAILLEUR: {
    id: 'RED_GEARS_BENT_DERAILLEUR', tier: 'RED', keefPose: 'stop',
    headline: 'Derailleur looks bent toward the wheel. Stop.',
    body: "If the rear mech goes into the spokes — and that's what a bent hanger eventually does — it destroys the wheel and can take the frame with it. That'll put you on the deck.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_CHAIN_BROKEN: {
    id: 'RED_CHAIN_BROKEN', tier: 'RED', keefPose: 'stop',
    headline: 'Snapped chain. Do not ride.',
    body: "A chain that snaps mid-pedal stroke puts you straight over the bars, especially climbing or out of the saddle. Don't try to ride it home.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_WHEELS_BROKEN_SPOKE: {
    id: 'RED_WHEELS_BROKEN_SPOKE', tier: 'RED', keefPose: 'stop',
    headline: 'Broken spoke. Stop.',
    body: "One spoke gone means the rest are overstressed. Wheels fail one spoke at a time, then quickly. Don't ride.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_WHEELS_SIDEWALL: {
    id: 'RED_WHEELS_SIDEWALL', tier: 'RED', keefPose: 'stop',
    headline: 'Sidewall failure. Stop.',
    body: "Casing showing through the tread, a bulge, or a cut deeper than the tread — the tyre will blow off the rim under load.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_WHEELS_CRACKED_RIM: {
    id: 'RED_WHEELS_CRACKED_RIM', tier: 'RED', keefPose: 'stop',
    headline: 'Cracked rim. Stop.',
    body: "Cracks at spoke nipples or along the rim mean the wheel is on borrowed time. Don't ride.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_HEADSET_KNOCK: {
    id: 'RED_HEADSET_KNOCK', tier: 'RED', keefPose: 'stop',
    headline: 'Knock through the head tube. Stop.',
    body: "A knock when you brake and rock the bike could be a loose headset — or a cracked steerer. They feel the same. The cracked steerer will fail without warning. We are not guessing this one.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_HEADSET_LOOSE_BARS: {
    id: 'RED_HEADSET_LOOSE_BARS', tier: 'RED', keefPose: 'stop',
    headline: 'Loose bars or stem. Do not ride.',
    body: "Bars rotating in the stem, or the stem rotating on the steerer — that's loss of steering control. No riding.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_FRAME_CARBON_CRACK: {
    id: 'RED_FRAME_CARBON_CRACK', tier: 'RED', keefPose: 'stop',
    headline: 'Visible crack on a carbon part. Stop.',
    body: "Carbon fails suddenly and badly — frame, fork, bars, stem, steerer, seatpost. Any visible crack or paint crazing at a clamp area means the part is done.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_BB_CRANK_PLAY: {
    id: 'RED_BB_CRANK_PLAY', tier: 'RED', keefPose: 'stop',
    headline: 'Side-to-side play in the cranks. Stop.',
    body: "A loose crank or BB will damage the frame, the axle, and put you down hard. One ride is enough to make it expensive — or dangerous.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_SUSPENSION_FORK: {
    id: 'RED_SUSPENSION_FORK', tier: 'RED', keefPose: 'stop',
    headline: 'Fork problem. Front-end failure on a descent is bad news. Stop.',
    body: "Knocking from the fork on bumps, fork stuck down, or won't compress at all — that's an internal failure. Front-end failure mid-descent is the scenario we are avoiding here.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_EBIKE_BATTERY_THERMAL: {
    id: 'RED_EBIKE_BATTERY_THERMAL', tier: 'RED', keefPose: 'stop',
    headline: 'Battery is swelling, hot, or smells. Stop NOW.',
    body: "That's thermal runaway risk. Lithium batteries that swell, get hot, smoke, or smell are a fire hazard. This is urgent.",
    actionLine: 'Phone Country Cycles immediately.',
    ctaId: 'CALL_SHOP_BATTERY',
  },
  RED_EBIKE_WATER_INGRESS: {
    id: 'RED_EBIKE_WATER_INGRESS', tier: 'RED', keefPose: 'stop',
    headline: 'Water inside the electrics. Stop.',
    body: "Pressure-washing or submersion forces water past seals into batteries, motors, and controllers. Symptoms can be intermittent now and serious later. Don't ride.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_EBIKE_EXPOSED_WIRING: {
    id: 'RED_EBIKE_EXPOSED_WIRING', tier: 'RED', keefPose: 'stop',
    headline: 'Exposed wiring on the e-system. Stop.',
    body: "Damaged motor cables, exposed conductors, or pinched wiring on an e-bike — short-circuit risk and battery fault risk.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
  RED_EBIKE_MOTOR_BURN: {
    id: 'RED_EBIKE_MOTOR_BURN', tier: 'RED', keefPose: 'stop',
    headline: 'Burning smell or grinding from the motor. Stop.',
    body: "Motor failure or worse. Don't ride. Disconnect the battery if you can do so safely.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_BATTERY',
  },
  RED_RECENT_CRASH_UNRESOLVED: {
    id: 'RED_RECENT_CRASH_UNRESOLVED', tier: 'RED', keefPose: 'stop',
    headline: 'Recent crash plus an unresolved noise or feel. Stop.',
    body: "Crashes hide cracks. Carbon, alloy, hangers, steerers, wheels — anything that took a knock can fail later. If something is not right after a crash, it gets checked before it gets ridden.",
    actionLine: 'Phone Country Cycles.',
    ctaId: 'CALL_SHOP_URGENT',
  },
};
